# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab05.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 578)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 0, 581, 541))
        self.graphicsView.setObjectName("graphicsView")
        self.colorBox = QtWidgets.QComboBox(self.centralwidget)
        self.colorBox.setGeometry(QtCore.QRect(610, 190, 171, 22))
        self.colorBox.setStyleSheet("background-color: rgb(217, 255, 255);")
        self.colorBox.setObjectName("colorBox")
        self.colorBox.addItem("")
        self.colorBox.addItem("")
        self.colorBox.addItem("")
        self.colorBox.addItem("")
        self.labelColor = QtWidgets.QLabel(self.centralwidget)
        self.labelColor.setGeometry(QtCore.QRect(610, 160, 171, 31))
        self.labelColor.setStyleSheet("background-color: rgb(140, 209, 255);")
        self.labelColor.setAlignment(QtCore.Qt.AlignCenter)
        self.labelColor.setObjectName("labelColor")
        self.labelMethod = QtWidgets.QLabel(self.centralwidget)
        self.labelMethod.setGeometry(QtCore.QRect(610, 230, 171, 31))
        self.labelMethod.setStyleSheet("background-color: rgb(140, 209, 255);")
        self.labelMethod.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMethod.setObjectName("labelMethod")
        self.paintBox = QtWidgets.QComboBox(self.centralwidget)
        self.paintBox.setGeometry(QtCore.QRect(610, 260, 171, 22))
        self.paintBox.setStyleSheet("background-color: rgb(217, 255, 255);")
        self.paintBox.setObjectName("paintBox")
        self.paintBox.addItem("")
        self.paintBox.addItem("")
        self.paintBut = QtWidgets.QPushButton(self.centralwidget)
        self.paintBut.setGeometry(QtCore.QRect(650, 300, 93, 28))
        self.paintBut.setStyleSheet("background-color: rgb(255, 145, 135);")
        self.paintBut.setObjectName("paintBut")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(610, 80, 171, 51))
        self.labelTitle.setStyleSheet("background-color: rgb(140, 209, 255);")
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setWordWrap(True)
        self.labelTitle.setObjectName("labelTitle")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu_1 = QtWidgets.QAction("Условие задачи")
        self.menubar.addAction(self.menu_1)
        self.menu_1.triggered.connect(self.task)
        self.menu_2 = QtWidgets.QAction("Об авторе")
        self.menubar.addAction(self.menu_2)
        self.menu_2.triggered.connect(self.info)
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.colorBox.setItemText(0, _translate("MainWindow", "Черный"))
        self.colorBox.setItemText(1, _translate("MainWindow", "Красный"))
        self.colorBox.setItemText(2, _translate("MainWindow", "Зеленый"))
        self.colorBox.setItemText(3, _translate("MainWindow", "Синий"))
        self.labelColor.setText(_translate("MainWindow", "Выберите цвет:"))
        self.labelMethod.setText(_translate("MainWindow", "Выберите способ закраски:"))
        self.paintBox.setItemText(0, _translate("MainWindow", "С задержкой"))
        self.paintBox.setItemText(1, _translate("MainWindow", "Без задержки"))
        self.paintBut.setText(_translate("MainWindow", "Закрасить"))
        self.labelTitle.setText(_translate("MainWindow", "Выберите параметры закраски"))

    def task(self):
        taskMes = QtWidgets.QMessageBox()
        taskMes.setWindowTitle("Условие задачи")
        taskMes.setText("Предоставить пользователю возможность ввода заполняемой области с последующим ее закрашиванием с задержкой и без.")
        taskMes.setIcon(QtWidgets.QMessageBox.Information)
        taskMes.exec_()

    def info(self):
        infoMes = QtWidgets.QMessageBox()
        infoMes.setWindowTitle("Об авторе")
        infoMes.setText("Лабораторная работа №5 'Растровые алгоритмы заполнения' была написана Параскун Софией, ИУ7-44Б")
        infoMes.setIcon(QtWidgets.QMessageBox.Information)
        infoMes.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
